### ISSUE TITLE
Pluign not banning

### ISSUE THREAD

**Issue by aleexolsson** [kadotcom/lifestolen#2]
Yo, tryna use the plugin, but when someone dies, they don't get banned, they respawn with 2hp, banOnDeath is true...

**Comment by kadotcom** [comment]
Hello,
May I ask what version you are using?
And could you also send an image of the config?

**Comment by aleexolsson** [comment]
Hi, I'm using 1.19.2 and the config is here
![lifestolen ts](https://user-images.githubusercontent.com/35394100/203537033-d1c34bd1-ccef-4a84-b09a-7c2de477d479.png)

**Comment by kadotcom** [comment]
What version of the plugin are you using?

**Comment by aleexolsson** [comment]
1.0 if I'm not mistaken

**Comment by kadotcom** [comment]
Ah.
Well the config looks good.
Are you getting an exact error in the console? If so, can you send it?

**Comment by aleexolsson** [comment]
No that's the weird thing, I'm not getting any error.

**Comment by kadotcom** [comment]
What server .jar are you using? (Paper, Spigot, Bukkit)

**Comment by aleexolsson** [comment]
Spigot, and Bungeecord if that's of interest

**Comment by kadotcom** [comment]
Maybe it’s a BungeeCord issue. I have no idea, I haven’t tested it on BungeeCord before.
I will still be looking into it later because I am not home right now. But for now that’s all I can think of.

**Comment by kadotcom** [comment]
For now I am closing this.

**Comment by aleexolsson** [comment]
Sounds fair, thanks for the help so far tho.
